### ISSUE TITLE
dbutil/litestream: do not force cgo builds

### ISSUE THREAD

**Issue by tnyeanderson** [mautrix/go-util#22]
Commit 0bf29a0 added `//go:build cgo` to the `dbutil/litestream` package files, which prevents any program importing this package from using `CGO_ENABLED=0` in their build process.

Was there a technical constraint that requires this to be added? It is very disappointing to find out I won't be able to build statically-linked binaries if this package is used.

**Comment by tnyeanderson** [comment]
Did some further testing and figured out how to remove this dependency entirely by using the `sqlite` [dialect](https://github.com/glebarez/go-sqlite) directly rather than using `sqlite3-fk-wal`.

It might be nice if this package used the pure Go implementation of sqlite linked here, if sqlite is the only reason cgo is needed.

I'll leave this open as a proposal, but I'm no longer blocked on this.

**Comment by tulir** [comment]
You can build statically linked binaries with cgo btw. All mautrix bridges have CI builds which are static with sqlite

**Comment by tnyeanderson** [comment]
Ah, I [see](https://github.com/mautrix/ci/blob/7884782b9dbf75f0ae27c7827d77aafbeb1f101f/go.yml#L20C48-L20C59) now that you use `GO_LDFLAGS="-extldflags -static"` in the builds. I didn't know about that trick, thanks!
